### ISSUE TITLE
Colors, Header, general feedback

### ISSUE THREAD

**Issue by carlomatik** [Jubeki/doctor-olivier-medical-practice#3]
Hello,

since your description on colors and the header was very vague, we would like to gather some Feedback of how it represents what you had in mind.
Furthermore feedback to all the provided websites would be appreciated, since the covid-19 and team websites are currently final for desktop screens.

Kind regards

**Comment by carlomatik** [comment]
@Jubeki @FM-2018

**Comment by Jubeki** [comment]
Hey @carlomatik ,

I can't find your pages on GitHub Pages. Link should be https://jubeki.github.io/doctor-olivier-medical-practice
Could you please provide images or push into the docs folder on the main branch?

Thanks.

**Comment by carlomatik** [comment]
Hello @Jubeki ,

we’re currently working on the develop Branch inside the „src“ folder.
If you still can’t find it I can push our progress onto the main branch as well.

kind regards

**Comment by ghost** [comment]
Hello @carlomatik and @muellale,

great to see the website is progressing! Unfortunately, we aren't quite satisfied with the state of the webpages, yet. Here's a list of comments:

## General / Header
* images aren't displayed at the URL
* The buttons in the navigation should be of equal height and maybe spaced apart a little
* At our opening times, Thursday and Friday are on the same line
* I personally find the color of the navbar to be too dark. I'd find the brighter color closer to doctor olivier's head in the image more suitable. 
* It'd be ideal if the image blended into the navbar somehow, or failing that, would have a suitable border to make it look better
* I'm not sure if I like how the buttons become completely see-through on hover. I think it would be better if they went to a slightly different color instead that'd still set them apart from the header
* We'd like a sans-serif font on the webpages
* In general, we would like a modern look and feel for the webpages
* It looks like part of the logo is cut off in the header on my 720p screen, and the opening hours overflow

## Covid-19
* We like the layout of this page! Unfortunately, the left bar with the video cannot be scrolled, and it doesn't fit on the screen completely with my 720p screen.
* The text part looks like.. well, a bunch of text, all of which is formatted bold. Some distinct formatting of headings would be nice!
* The diagrams are looking good! But a heading like "Current developments" would be good.

## Our Team
* Like in Covid-19, more distinct formatting is wished
* The images are HUGE! Please make it so the images can comfortably fit into the browser window. Maybe put the text next to the images and see if that looks good

## Blog
* We do not like the bars / lines around the sections of the layout. We would like you to find a different solution
* It feels strange to have a huge button on top of each article. How about just a heading, and a read-more button below the article introduction?

## Services
* Like the other pages, some more involved and modern formatting would be good

## Contact us
* I like the idea with the image sticking in place even when scrolling through the content
* Again, formatting.


Thinking about it, it seems our branding color is used only in the header, the buttons and the lines on the blog. Maybe you can find more ways to include it into the webpage, e.g. table heads, ...

**Comment by carlomatik** [comment]
Hello @FM-2018 @Jubeki ,

your given feedback has been taken into consideration and the pages have been modified accordingly.
Please look over them again and tell us if you found any new feedback.
Please note, that the blog is taken care of by @muellale and has not been updated yet.

Kind regards

**Comment by Jubeki** [comment]
Hey @carlomatik and @muellale ,

I am not so sure about the current header. You can also change the background color to something neutral and just use our brand color for buttons, links and so on. Also please move the buttons more apart and remove the rounding. You could also move the navigation in another row so that you have more space for the header information.

On some pages are still serif font-faces used please use the same font on all sites.

I like the current contact and covid-19 pages. There are still some spacing and sizing issues but these can be fixed later on.

In my opinion the images on the team site should be smaller.

Best regards
Julius

**Comment by carlomatik** [comment]
Hello @FM-2018 @Jubeki ,

please consider the Header of the contact us page and tell me what you think about the changes we made.

Kind regards

**Comment by Jubeki** [comment]
The header looks definitely better than before. it seems there are still some issues with the margin of the main content to the top because something is hidden beneath the header.

**Comment by carlomatik** [comment]
@Jubeki I do not have these issues, can you please describe them in more detail or add a screenshot please?

**Comment by Jubeki** [comment]
![Screenshot 2021-01-08 at 12 14 40](https://user-images.githubusercontent.com/15707543/104009423-4e4f2800-51ab-11eb-8868-b921d6108233.png)
![Screenshot 2021-01-08 at 12 15 15](https://user-images.githubusercontent.com/15707543/104009435-5313dc00-51ab-11eb-97a1-fa7edb1527ef.png)

**Comment by carlomatik** [comment]
@Jubeki does the content disappear after you resize the height of the screen?

**Comment by Jubeki** [comment]
I have the browser in fullscreen on two different displays: 3440x1440 and 1792x1120 the result can you see in my last comment
