### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by carlomatik** [Jubeki/doctor-olivier-medical-practice#4]
Hello @Jubeki @FM-2018,

I just finished to contact us webpage and wanted to know how you intended the contact form.
Is it supposed to be at the end of the contact us page, or should it rather be a separate webpage which is reachable when clicking on the image?

Kind regards

**Comment by ghost** [comment]
Hey @carlomatik ,

which image are you talking about exactly? If you're referring to the AskMyGP image, you should make it link to the link we've given in the contact.md description file. It's https://my.askmygp.uk/?c=S71379.

If you're referring to the online contact formular we mentioned at the end of the contact.md, this should ideally be located and usable at the end of the webpage. The user can enter his info and request into the form fields, and a click onto a Send button will send their message over to us (Send button does not need to actually do something)

**Comment by carlomatik** [comment]
Good evening @FM-2018 ,

the Image you refer to is currently opening a new tab and opens the mentioned link.

Okay, that answers my question. However I find it odd that there is this contact form and a second one thats for making appointmens.
Can you explain how these two are meant to be different? If the contact form on the contact us site is NOT to make appointments I dont really understand its purpose.

Kind regards

**Comment by ghost** [comment]
Hey @carlomatik ,

basically, the appointment-booker is supposed to automate the process of booking an appointment. We do not want to have to handle several requests a day that are just about arranging standard appointments like the ones mentioned in appointment-booking.md. If however they want an appointment that's for some reason not covered by the appointment booker, or they have a different wish they want to discuss with us, the contact form can be used.
