### ISSUE TITLE
Git Pages source

### ISSUE THREAD

**Issue by carlomatik** [Jubeki/doctor-olivier-medical-practice#5]
Hello @FM-2018 @Jubeki ,

--- TO BE IGNORED ---
_I can not work on the main branch, I can not tell why, maybe because of permissions? but I can not push any changes on the branch since these changes arent recognised and it tells me that its up to date (which its obviously not). Hence why we will be working only on the develop branch, so please ignore the main_ 
--- TO BE IGNORED ---

Please setup the docs Folder in the *main* branch as the Git Pages source.

Kind regards

**Comment by ghost** [comment]
Hey @carlomatik ,

as far as I know Github pages has already been setup in the main branch docs folder. In any case, our URL https://jubeki.github.io/doctor-olivier-medical-practice/ seems to be functioning now. So, thanks for merging!
