### ISSUE TITLE
GitHub Pages annoying Bug

### ISSUE THREAD

**Issue by carlomatik** [Jubeki/doctor-olivier-medical-practice#6]
Hello @Jubeki @FM-2018 ,

note that the GitHub Pages functionality has a really annoying bug where it does not compile the website correctly if the CSS files have minor changes. To be specific colors are not displayed in the GitHub Pages link as they are specified inside the CSS files. Because of this the website has this greyish background look instead of white.
I do not know why this is the case or how to resolve it.

Kind regards

**Comment by carlomatik** [comment]
This bug contains to bother on the latest commit.

**Comment by carlomatik** [comment]
This seems to be an issue with my local cache of the browser, if you could confirm this to be the case (this would be if you can view the webpages and dont have errors like the content moving behind the header when resizing) you can close this issue.

**Comment by Jubeki** [comment]
Okay we will then just empty our cached accordingly if something like this happens again.
