### ISSUE TITLE
Index Startpage

### ISSUE THREAD

**Issue by carlomatik** [Jubeki/doctor-olivier-medical-practice#9]
Hello @FM-2018 @Jubeki ,

please let me know what you think about the start page and if it meets what you had in mind.
Since the description of this page was extremely vague I kind of just did what I envisioned when thinking about it.

Kind regards

**Comment by ghost** [comment]
Hey @carlomatik ,

the layout of the homepage looks good to me! But the phrase "We offer Service" sounds awkward. Maybe change it to "Versatile services" or "Various services", so it sounds like a quality of the practice, like the "Competent team" does. I'd also change the heading "Pandemic" to "About the Pandemic" or "Pandemic Information".

I see below the home page there's a "Slideshow container, Manual Slideshow" that however does nothing on my Firefox. Is this still work in progress?
